### ISSUE TITLE
Runtime `pcap_lib_version` probe

### ISSUE THREAD

**Issue by sekineh** [rust-pcap/pcap#137]
It decreases determinism.
I feel like it should be enabled when `--features runtime-version-probe` (the name is example-purpose only) is specified.

**Comment by sekineh** [comment]
Need to see whether it enables better API...
Problem space looks like rather big.

**Comment by sekineh** [comment]
`libloading` could be used to determine which symbol is available in the given dll....
https://docs.rs/libloading/0.6.3/libloading/

**Comment by Wojtek242** [comment]
Copied from #118:

One benefit of runtime checking is that it would allow for said developer to support a super new version of libpcap, but only the features that use the newest API calls would be unavailable to the user. A potential scenario is that 98% of a particular library uses the 1.5.0 API, but the 2% uses API from 1.7.2. With dynamic runtime checking the users of that library still get to use 98% of the functionality rather than 0%. However, this is easier said than done as libpcap also sometimes changes the behaviour of existing API calls across versions (e.g. immediate mode on Linux).

**Comment by Wojtek242** [comment]
Since the issue was opened the need for runtime version detection hasn't arisen. I suspect that anybody using `pcap` will either compile on the target or if distributing a binary to have a particular environment. Closing this issue until an actual need may arise.
